title: "Shyamal Suhana Chandra"
description: "Chief Engineer (Manager) · Apple-like animated resume"
url: "" # Set this to your GitHub Pages URL, e.g. https://username.github.io
baseurl: "" # Set if using a project page, e.g. /my-resume

markdown: kramdown
theme: null

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

